compobulator_project/compobulator_app/urls.py
from django.conf.urls import url;
from compobulator_app import views;

app_name = 'compobulator_app';

urlpatterns = [
    url(r'^mp_archetype_list/$', views.ArchetypeListView.as_view(), name='urlan_list'),
    # url(r'^(?P<pk>[-\w]+)/$', views.ArchetypeDetailView.as_view(), name='urlan_detail'),
    url(r'^mp_archetype_form/', views.mp_archetype_form_view, name='url_arch_form'), # Need name for same reason in templates
    url(r'^(?P<pk>\d+)/$', views.ArchetypeDetailView.as_view(), name='url_arch_detail'),
    # url(r'^create/$', views.ArchetypeCreateView.as_view(), name='url_arch_create'),
    # url(r'^update/(?P<pk>\d+)/$', views.ArchetypeUpdateView.as_view(), name='url_arch_update'),
    # url(r'^delete/(?P<pk>\d+)/$', views.ArchetypeDeleteView.as_view(), name='url_arch_delete'),
    url(r'^mp_element_list/$', views.ElementListView.as_view(), name='urlen_list'),
    # url(r'^(?P<pk>[-\w]+)/$', views.ElementDetailView.as_view(), name='urlen_detail'),
    url(r'^mp_element_form/', views.mp_element_form_view, name='url_elem_form'), # Need name for same reason in templates
    url(r'^(?P<pk>\d+)/$', views.ElementDetailView.as_view(), name='url_elem_detail'),
    # url(r'^(?P<slug>[-\w]+)/$', views.ElementDetailView.as_view(), name='mp_element-detail'),
    # url(r'^create/$', views.ElementCreateView.as_view(), name='url_elem_create'),
    # url(r'^update/(?P<pk>\d+)/$', views.ElementUpdateView.as_view(), name='url_elem_update'),
    # url(r'^delete/(?P<pk>\d+)/$', views.ElmentDeleteView.as_view(), name='url_elem_delete'),

];

compobulator_project/compobulator_app/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.
class Mp_archetype(models.Model):
    id1 = models.CharField(primary_key=True, max_length=64, unique=True, blank=False)
    gid = models.UUIDField(default=uuid.uuid4)
    crtdate = models.DateField()
    crtby = models.UUIDField(default=uuid.uuid4)

    def __str__(self):
        return self.crtby + '-' + str(self.crtdate) + '-' + self.id

    def get_absolute_url(self):
        return reverse("compobulator_app:detail", kwargs={'pk':self.pk})

class Mp_element(models.Model):
    fldname = models.CharField(primary_key=True, max_length=64, unique=True, blank=False)
    fldtype = models.CharField(max_length=64)
    gid = models.UUIDField(default=uuid.uuid4)
    archetypeid = models.UUIDField(default=uuid.uuid4)
    crtdate = models.DateField()
    crtby = models.UUIDField(default=uuid.uuid4)

    def __str__(self):
        return self.crtby + '-' + str(self.crtdate) + '-' + self.id

    def get_absolute_url(self):
        return reverse("compobulator_app:url_elem_detail", kwargs={'pk':self.pk})

compobulator_project/compobulator_app/forms.py
from django import forms
from django.core import validators
from compobulator_app.models import Mp_archetype, Mp_element

class mp_archetype_model_form(forms.ModelForm):
    class Meta:
        model = Mp_archetype
        fields = '__all__'

    def clean(self):
        all_clean_data = super().clean()

class mp_element_model_form(forms.ModelForm):
    class Meta:
        model = Mp_element
        fields = '__all__'

    def clean(self):
        all_clean_data = super().clean()

compobulator_project/compobulator_app/views.py
from django.shortcuts import render
from compobulator_app.forms import mp_archetype_model_form, mp_element_model_form
from django.views.generic import TemplateView, CreateView, ListView, DetailView  # For the cbv's
from compobulator_app import models

class IndexView(TemplateView):
    template_name = 'compobulator_app/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectMeId'] = "Here's some text for injection!"
        return context

class ArchetypeListView(ListView):
    context_object_name = 'alvcon_list'
    model = models.Mp_archetype
    template_name = 'compobulator_app/mp_archetype_list.html'

class ArchetypeDetailView(DetailView):
    context_object_name = 'advcon_details'
    model = models.Mp_archetype
    template_name = 'compobulator_app/mp_archetype_detail.html'

class ElementListView(ListView):
    context_object_name = 'elvcon_list'
    model = models.Mp_element
    template_name = 'compobulator_app/mp_element_list.html'

class ElementDetailView(DetailView):
    context_object_name = 'edvcon_details'
    model = models.Mp_element
    template_name = 'compobulator_app/mp_element_detail.html'

def index(request):
    return render(request, 'compobulator_app/index.html')

def mp_archetype_form_view(request):
    form = mp_archetype_model_form()

    if request.method == 'POST':
        form = mp_archetype_model_form(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('Error: mp_archetype_model_form is invalid!')
    return render(request, 'compobulator_app/mp_archetype_form.html', {'form': form})

def mp_element_form_view(request):
    form = mp_element_model_form()

    if request.method == 'POST':
        form = mp_element_model_form(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('Error: mp_element_model_form is invalid!')
    return render(request, 'compobulator_app/mp_element_form.html', {'form': form})

compobulator_project/compobulator_app/templates/compobulator_app/compobulator_app_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Meed Partners Compobulator!</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"></link>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"></link>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"></link>
      <link rel="stylesheet" href="{% static "customthemes/css/meedmaster.css" %}"></link>
      <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"></link>
  </head>
  <body>
    <div clas="container">
      <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'compobulator_app:urlan_list' %}">ArchetypesList</a></li>
          <li><a class="navbar-brand" href="{% url 'compobulator_app:url_arch_form' %}">ArchetypesForm</a></li>
          <li><a class="navbar-brand" href="{% url 'compobulator_app:urlen_list' %}">ElementsList</a></li>
          <li><a class="navbar-brand" href="{% url 'compobulator_app:url_elem_form' %}">ElementsForm</a></li>
          <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </nav>
      <div class="jumbotron">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

compobulator_project/compobulator_app/templates/compobulator_app/mp_archetype_detail.html
{% extends 'compobulator_app/compobulator_app_base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to the Archetypes Detail Page!</h1>
      <h2>Archetype Details:</h2>
      <p>Id: {{advcon_details.id1}}</p>
      <p>Gid: {{advcon_details.gid}}</p>
      <p>Create Date: {{advcon_details.crtdate}}</p>
      <p>Created By: {{advcon_details.crtby}}</p>
    </div>
  {% endblock %}

compobulator_project/compobulator_app/templates/compobulator_app/mp_archetype_form.html
{%  extends "compobulator_app/compobulator_app_base.html" %}
  {% block body_block %}
    <h2>Fill out the "mp_archetype_model_form" form ...</h2>
    <form method='POST'>
      {% csrf_token %}
      {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit"></input>
    </form>
  {% endblock %}

compobulator_project/compobulator_app/templates/compobulator_app/mp_archetype_list.html
{%  extends "compobulator_app/compobulator_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h2>Here is the list of archetypes!</h2>
    <ol>
      {% for mpa in alvcon_list %}
        <h2><li><a href="{{ mpa.id }}">{{ mpa.id1 }}</a></li></h2>
      {% empty %}
        <li>No Archetypes created as yet.</li>
      {% endfor %}
    </ol>
  </div>
{% endblock %}

compobulator_project/compobulator_app/templates/compobulator_app/mp_element_detail.html
{% extends 'compobulator_app/compobulator_app_base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to the Elements Detail Page!</h1>
      <h2>Element Details:</h2>
      <p>Id: {{edvcon_details.fldname}}</p>
      <p>Id: {{edvcon_details.fldtype}}</p>
      <p>Gid: {{edvcon_details.gid}}</p>
      <p>Archetypeid: {{edvcon_details.archetypeid}}</p>
      <p>Create Date: {{edvcon_details.crtdate}}</p>
      <p>Created By: {{edvcon_details.crtby}}</p>
    </div>
  {% endblock %}

compobulator_project/compobulator_app/templates/compobulator_app/mp_element_form.html
{%  extends "compobulator_app/compobulator_app_base.html" %}
  {% block body_block %}
    <h2>Fill out the "mp_element_model_form" form ...</h2>
    <form method='POST'>
      {% csrf_token %}
      {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit"></input>
    </form>
  {% endblock %}

compobulator_project/compobulator_app/templates/compobulator_app/mp_element_list.html
{%  extends "compobulator_app/compobulator_app_base.html" %}
{% block body_block %}
  <h2>Here is the list of elements!</h2>
    <ol>
      {% for mpe in elvcon_list %}
        <h2><li><a href="{{ mpe.id }}">{{ mpe.fldname }}</a></li></h2>
      {% empty %}
        <h4><li>No Elements created as yet.</li></h4>
      {% endfor %}
    </ol>
{% endblock %}